# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

[alembic:env]
# add project root to PYTHONPATH so `app` is importable
prepend_sys_path = .
# use os.pathsep (default) to split multiple version_locations if you add them
version_path_separator = os

# Default DB URL (will be overridden in env.py if you set it there)
sqlalchemy.url = sqlite:///./alokazi.db

[post_write_hooks]
# (optional) run formatters / linters on new revision files
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
