# File: alembic/versions/e07355b3b8aa_baseline_initial_schema.py

"""baseline initial schema

Revision ID: e07355b3b8aa
Revises: 
Create Date: 2025-05-21 08:00:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e07355b3b8aa'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        # … other User columns …
    )
    op.create_table(
        'business',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('short_description', sa.String(), nullable=False),
        sa.Column('town_or_district', sa.String(), nullable=False),
        sa.Column('contact_phone', sa.String(), nullable=False),
        sa.Column('contact_email', sa.String(), nullable=False),
        sa.Column('contact_website', sa.String(), nullable=True),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('region_code', sa.String(), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('average_rating', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('digital_address', sa.String(), nullable=True),
        sa.Column('code', sa.String(), nullable=True),
        sa.Column('postal_code', sa.String(), nullable=True),
        sa.Column('district_name', sa.String(), nullable=True),
        sa.Column('road_name', sa.String(), nullable=True),
        sa.Column('house_no', sa.String(), nullable=True),
        sa.Column('full_address', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['user.id']),
    )
    # … repeat op.create_table(...) for Home, FavourablePlace, Contribution, Share,
    #     LocationShare, PostalCode, Road, etc., exactly as in your original migration …
    # Note: the following line was removed because that index no longer exists:
    #     op.drop_index('ix_business_digital_address', table_name='business')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business')
    op.drop_table('user')
    # … repeat op.drop_table(...) for every other table you created above …
    # ### end Alembic commands ###
