"""add full_address to location_share

Revision ID: ac67b01cac75
Revises: aaba8bc1c4fc
Create Date: 2025-05-19 05:30:03.474715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac67b01cac75'
down_revision: Union[str, None] = 'aaba8bc1c4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_streetindex_street', table_name='streetindex')
    op.drop_table('streetindex')
    op.drop_index('ix_share_shared_with', table_name='share')
    op.drop_table('share')
    op.drop_index('ix_favourableplace_code', table_name='favourableplace')
    op.drop_index('ix_favourableplace_digital_address', table_name='favourableplace')
    op.drop_table('favourableplace')
    op.drop_index('ix_postalcode_country_code', table_name='postalcode')
    op.drop_index('ix_postalcode_postal_code', table_name='postalcode')
    op.drop_table('postalcode')
    op.drop_index('ix_business_code', table_name='business')
    op.drop_index('ix_business_digital_address', table_name='business')
    op.drop_table('business')
    op.drop_index('ix_contribution_digital_address', table_name='contribution')
    op.drop_table('contribution')
    op.drop_table('road')
    op.drop_index('ix_locationshare_code', table_name='locationshare')
    op.drop_index('ix_locationshare_digital_address', table_name='locationshare')
    op.drop_table('locationshare')
    op.drop_index('ix_home_code', table_name='home')
    op.drop_index('ix_home_digital_address', table_name='home')
    op.drop_table('home')
    op.drop_index('ix_user_country_code', table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_name', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.Column('country_code', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.create_index('ix_user_country_code', 'user', ['country_code'], unique=False)
    op.create_table('home',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('digital_address', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_home_digital_address', 'home', ['digital_address'], unique=False)
    op.create_index('ix_home_code', 'home', ['code'], unique=1)
    op.create_table('locationshare',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('digital_address', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_locationshare_digital_address', 'locationshare', ['digital_address'], unique=False)
    op.create_index('ix_locationshare_code', 'locationshare', ['code'], unique=1)
    op.create_table('road',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('geometry', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('submitted_by', sa.INTEGER(), nullable=False),
    sa.Column('submitted_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contribution',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contrib_type', sa.VARCHAR(length=4), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('wkt', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('is_approved', sa.BOOLEAN(), nullable=False),
    sa.Column('submitted_by_user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('digital_address', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contribution_digital_address', 'contribution', ['digital_address'], unique=False)
    op.create_table('business',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('short_description', sa.VARCHAR(), nullable=True),
    sa.Column('town_or_district', sa.VARCHAR(), nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(), nullable=True),
    sa.Column('contact_email', sa.VARCHAR(), nullable=True),
    sa.Column('contact_website', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('region_code', sa.VARCHAR(), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('average_rating', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('digital_address', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_business_digital_address', 'business', ['digital_address'], unique=False)
    op.create_index('ix_business_code', 'business', ['code'], unique=1)
    op.create_table('postalcode',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('country_code', sa.VARCHAR(), nullable=False),
    sa.Column('admin_name1', sa.VARCHAR(), nullable=False),
    sa.Column('admin_name2', sa.VARCHAR(), nullable=True),
    sa.Column('place_name', sa.VARCHAR(), nullable=False),
    sa.Column('postal_code', sa.VARCHAR(), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_postalcode_postal_code', 'postalcode', ['postal_code'], unique=False)
    op.create_index('ix_postalcode_country_code', 'postalcode', ['country_code'], unique=False)
    op.create_table('favourableplace',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=True),
    sa.Column('label', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('digital_address', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_favourableplace_digital_address', 'favourableplace', ['digital_address'], unique=False)
    op.create_index('ix_favourableplace_code', 'favourableplace', ['code'], unique=1)
    op.create_table('share',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('resource_id', sa.INTEGER(), nullable=False),
    sa.Column('shared_with', sa.VARCHAR(), nullable=False),
    sa.Column('shared_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_share_shared_with', 'share', ['shared_with'], unique=False)
    op.create_table('streetindex',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('street', sa.VARCHAR(), nullable=False),
    sa.Column('geom_wkb', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_streetindex_street', 'streetindex', ['street'], unique=False)
    # ### end Alembic commands ###
